
#Common configuration settings
[common]
	#Level of debug messages to be shown in the logs.
	#0-All debug messages. 1-Warnings/Errors only. 2-Errors only. 3-No debug messages.
	#Note: All debug messages will still be sent debug.log regardless of settings.
	#Range: 0 ~ 3
	debugLevel = 0

	#Villager Related Settings.
	[common.villagers]
		#Whether the wandering trader will have additional trades that allow you to buy misc items with money.
		addCustomWanderingTrades = false
		#Whether the banker villager profession will have any registered trades. The banker sells Lightman's Currency items for coins.
		addBanker = false
		#Whether the cashier villager profession will have any registered trades.. The cashier sells an amalgamation of vanilla traders products for coins.
		addCashier = false

	#Entity loot settings. Accepts entity ids (i.e. minecraft:zombie)
	[common.entity_loot]
		#Whether coins can be dropped by entities. Does not effect chest loot generation.
		enableEntityDrops = false
		#Whether coins can be dropped by entities that were spawned by the vanilla spawner.
		enableSpawnerEntityDrops = false
		#Entities that will occasionally drop copper coins.
		copper = []
		#Entities that will occasionally drop copper -> iron coins.
		iron = []
		#Entities that will occasionally drop copper -> gold coins.
		gold = []
		#Entities that will occasionally drop copper -> emerald coins.
		emerald = []
		#Entities that will occasionally drop copper -> diamond coins.
		diamond = []
		#Entities that will occasionally drop copper -> netherite coins.
		netherite = []
		#Entities that will drop a large amount of copper coins.
		boss_copper = []
		#Entities that will drop a large amount of copper -> iron coins.
		boss_iron = []
		#Entities that will drop a large amount of copper -> gold coins.
		boss_gold = []
		#Entities that will drop a large amount of copper -> emerald coins.
		boss_emerald = []
		#Entities that will drop a large amount of copper -> diamond coins.
		boss_diamond = []
		#Entities that will drop a large amount of copper -> netherite coins.
		boss_netherite = []

	#Chest loot settings.
	[common.chest_loot]
		#Whether coins can spawn in chests Does not effect entity loot drops.
		enableChestLoot = false
		#Chests that will occasionally spawn copper coins.
		copper = []
		#Chests that will occasionally spawn copper -> iron coins.
		iron = []
		#Chests that will occasionally spawn copper -> gold coins.
		gold = []
		#Chests that will occasionally spawn copper -> emerald coins.
		emerald = []
		#Chests that will occasionally spawn copper -> diamond coins.
		diamond = []
		#Chests that will occasionally spawn copper -> netherite coins.
		netherite = []

